[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "frontend"

# Blob Store
[[blobs]]
  name = "coletas"

# Rotas
[[redirects]]
  from = "/api/coletar"
  to = "/.netlify/functions/coletar"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/admin"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
